import 'package:flutter/material.dart';
import 'package:typicons_flutter/typicons.dart';

class CryptoData {
  static final getData = [
    {
      'name': 'HardDisk',
      'symbol': 'Dell Edge',
      'icon': Typicons.database,
      'iconColor': Colors.redAccent,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.black,
      'value': '\Rs 20,00',
    },
    {
      'name': 'Camera',
      'symbol': 'Samsung',
      'icon': Typicons.camera,
      'iconColor': Colors.deepOrange,
      'change': 'Blue Ray',
      'changeValue': 'Special Offer',
      'changeColor': Colors.green,
      'value': '\Rs 110,0',
    },
    {
      'name': 'Camera',
      'symbol': 'Logitech',
      'icon': Typicons.camera,
      'iconColor': Colors.orange,
      'change': 'Back Lit',
      'changeValue': 'Special Offer',
      'changeColor': Colors.black,
      'value': '\Rs 10,0',
    },
    {
      'name': 'Headphones',
      'symbol': 'Dell Edge',
      'icon': Typicons.headphones,
      'iconColor': Colors.black,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.green,
      'value': '\Rs 20,0',
    },
    {
      'name': 'TV',
      'symbol': 'Samsung',
      'icon': Typicons.shopping_cart,
      'iconColor': Colors.lightBlueAccent,
      'change': 'Blue Ray',
      'changeValue': 'Special Offer',
      'changeColor': Colors.red,
      'value': '\Rs 110,0',
    },
    {
      'name': 'Laptop',
      'symbol': 'Dell Edge',
      'icon': Typicons.archive,
      'iconColor': Colors.greenAccent,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.blue,
      'value': '\Rs 20,0',
    },
    {
      'name': 'TV',
      'symbol': 'Samsung',
      'icon': Typicons.shopping_cart,
      'iconColor': Colors.deepPurpleAccent,
      'change': 'Blue Ray',
      'changeValue': 'Special Offer',
      'changeColor': Colors.indigo,
      'value': '\Rs 1100',
    },
    {
      'name': 'Laptop',
      'symbol': 'Dell Edge',
      'icon': Typicons.arrow_right_outline,
      'iconColor': Colors.amber,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.lightBlueAccent,
      'value': '\Rs 20,0',
    },
    {
      'name': 'Laptop',
      'symbol': 'Dell Edge',
      'icon': Typicons.at,
      'iconColor': Colors.redAccent,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.indigoAccent,
      'value': '\Rs 20,0',
    },
    {
      'name': 'Laptop',
      'symbol': 'Dell Edge',
      'icon': Typicons.zoom_outline,
      'iconColor': Colors.orange,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.green,
      'value': '\Rs 20,0',
    },
    {
      'name': 'Laptop',
      'symbol': 'Dell Edge',
      'icon': Typicons.weather_cloudy,
      'iconColor': Colors.teal,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.tealAccent,
      'value': '\Rs 20,0',
    },
    {
      'name': 'Laptop',
      'symbol': 'Dell Edge',
      'icon': Typicons.anchor,
      'iconColor': Colors.amberAccent,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.deepOrangeAccent,
      'value': '\Rs 20,0',
    },
    {
      'name': 'Laptop',
      'symbol': 'Dell Edge',
      'icon': Typicons.anchor,
      'iconColor': Colors.orange,
      'change': '16GB Ram, Monitor, Keyboard, Mouse',
      'changeValue': 'Special Offer',
      'changeColor': Colors.green,
      'value': '\Rs 20,0',
    },
  ];
}
